### ISSUE TITLE
add smooth parameter for line plot

### ISSUE THREAD

**Issue by devcrocod** [AndreiKingsley/lib-ggdsl#21]

**Comment by devcrocod** [comment]
```kotlin
plot(...) {
    ...
    line {
        smooth(true)
    }
}
```

**Comment by AndreiKingsley** [comment]
Perhaps, just `smooth = true`? It's not an Aes, I think.

**Comment by devcrocod** [comment]
via features?

And I'm confused by the API, when we have different ways of setting parameters for plotting:
```kotlin
plot(data) {
    x(xaxis)
    line {
        y(yaxis)
        width(3) // !
        smooth = true // !!
    }
}
```

**Comment by AndreiKingsley** [comment]
Well yeah, of course it's plotting parameter, but it can hardly be called an aesthetic attribute. I think the best option is to move the setting into `line` arguments:
```
line(smooth = true) {
    ...
}
```
And this concerns to all other similar parameters.
But on the other hand, user possibly will be looking for this parameter in context, idk.
